kind: pipeline
type: docker
name: local-build-run

steps:
  - name: build-image
    image: docker:24.0
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t my-vue-app:latest .

  - name: run-container
    image: docker:24.0
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker rm -f my-vue-app || true
      - docker run -d -p 8081:80 --name my-vue-app my-vue-app:latest

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main