kind: pipeline
type: docker
name: local-build-run

steps:
  - name: build-app
    image: node:18
    commands:
      - npm install
      - npm run build

  - name: build-image
    image: plugins/docker
    settings:
      repo: my-vue-app
      tags: latest
      dockerfile: ./Dockerfile
      # 如果你只想本地 build，不推 registry，可以加上：
      dry_run: true

  # 如果想要在 pipeline 内测试运行容器，可以直接用 services
services:
  - name: vue-app
    image: my-vue-app:latest
    ports:
      - 8081:80

trigger:
  branch:
    - main
